<script setup lang="ts">
import { Refresh } from "@element-plus/icons-vue";
import { ElMessage } from "element-plus";
import { ref, watch } from "vue";
import { errorMessage } from "@/api/client";
import { getCustomers, getSalesOrders, getTradeSummary } from "@/api/trade";
import { useFarmStore } from "@/stores/farm";
import type { Customer, SalesOrder, TradeSummary } from "@/types/trade";
const farmStore = useFarmStore(); const loading = ref(false); const customers = ref<Customer[]>([]); const orders = ref<SalesOrder[]>([]); const summary = ref<TradeSummary | null>(null);
async function load() { const farmId = farmStore.currentFarmId; if (!farmId) return; loading.value = true; try { [customers.value, orders.value, summary.value] = await Promise.all([getCustomers(farmId), getSalesOrders(farmId), getTradeSummary(farmId)]); } catch (error) { ElMessage.error(errorMessage(error)); } finally { loading.value = false; } }
watch(() => farmStore.currentFarmId, () => void load(), { immediate: true });
</script>
<template><section class="farm-page resource-page"><header class="page-header farm-page-header"><div><p class="eyebrow">TRADE & FINANCE</p><h1>销售经营</h1><p>{{ farmStore.currentFarm?.name ?? "尚未选择农场" }} · 客户、销售和收款</p></div><el-button :icon="Refresh" @click="load">刷新</el-button></header><el-empty v-if="!farmStore.currentFarm" description="暂无可用农场" /><template v-else><el-descriptions v-loading="loading" :column="3" border direction="vertical"><el-descriptions-item label="已过账销售">¥ {{ summary?.postedSalesAmount ?? "0.00" }}</el-descriptions-item><el-descriptions-item label="已收款">¥ {{ summary?.receivedAmount ?? "0.00" }}</el-descriptions-item><el-descriptions-item label="应收余额">¥ {{ summary?.receivableAmount ?? "0.00" }}</el-descriptions-item></el-descriptions><div class="trade-grid"><section class="farm-table-shell"><div class="section-heading"><h2>客户</h2><span>{{ customers.length }} 个</span></div><el-table :data="customers" row-key="id" empty-text="暂无客户"><el-table-column prop="code" label="编号" width="120" /><el-table-column prop="name" label="名称" min-width="150" /><el-table-column prop="contact" label="联系人" min-width="120" /><el-table-column prop="phone" label="电话" min-width="140" /></el-table></section><section class="farm-table-shell"><div class="section-heading"><h2>销售单</h2><span>{{ orders.length }} 张</span></div><el-table :data="orders" row-key="id" empty-text="暂无销售单"><el-table-column prop="orderNo" label="单号" min-width="140" /><el-table-column prop="customerName" label="客户" min-width="140" /><el-table-column prop="saleDate" label="日期" width="120" /><el-table-column label="金额" width="120" align="right"><template #default="scope">¥ {{ scope.row.totalAmount }}</template></el-table-column><el-table-column prop="status" label="状态" width="100" /></el-table></section></div></template></section></template>
<style scoped>.trade-grid { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 20px; margin-top: 20px; }.section-heading { display: flex; justify-content: space-between; align-items: baseline; padding: 18px 20px 0; }.section-heading h2 { margin: 0 0 12px; font-size: 16px; }.section-heading span { color: var(--el-text-color-secondary); font-size: 13px; }@media (max-width: 760px) { .trade-grid { grid-template-columns: 1fr; } }</style>
