$env:AGRI_HARNESS_ROOT = 'G:\deepseek-harness-master\deepseek-harness-master'
$env:AGRI_HARNESS_WORKSPACE = 'G:\deepseek-harness-master\deepseek-harness-master'
$env:AGRI_HARNESS_PATCH = 'D:\zongheguanlixitong\deploy\harness\cordis.patch.yml'
$env:AGRI_HARNESS_PLUGIN_PATH = 'G:\deepseek-harness-master\deepseek-harness-master\packages\extensions\agri-agent-tools\src\index.ts'
$env:AGRI_HARNESS_DSH_HOME = 'D:\zongheguanlixitong\.dsh-agri'
$env:AGRI_BACKEND_BASE_URL = 'http://127.0.0.1:5000'
$env:AGRI_GATEWAY_PORT = '15100'
$env:AGRI_GATEWAY_PUBLIC_URL = 'http://127.0.0.1:15100'
Set-Location 'G:\deepseek-harness-master\deepseek-harness-master'
pnpm exec tsx 'D:\zongheguanlixitong\deploy\harness\gateway\index.ts'
