"""Add customers, sales orders and payments."""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

revision = "0020_trade_sales"
down_revision = "0019_crop_operation_templates"
branch_labels = None
depends_on = None

def upgrade():
    op.create_table("customers", sa.Column("id", mysql.BIGINT(unsigned=True), primary_key=True, autoincrement=True), sa.Column("farm_id", mysql.BIGINT(unsigned=True), nullable=False), sa.Column("code", sa.String(20), nullable=False), sa.Column("name", sa.String(100), nullable=False), sa.Column("contact", sa.String(40)), sa.Column("phone", sa.String(30)), sa.Column("address", sa.String(255)), sa.Column("is_active", sa.Boolean(), server_default="1", nullable=False), sa.Column("created_by_id", mysql.BIGINT(unsigned=True), nullable=False), sa.Column("updated_by_id", mysql.BIGINT(unsigned=True), nullable=False), sa.Column("created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False), sa.Column("updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False), sa.ForeignKeyConstraint(["farm_id"], ["farms.id"], ondelete="RESTRICT"), sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="RESTRICT"), sa.ForeignKeyConstraint(["updated_by_id"], ["users.id"], ondelete="RESTRICT"), sa.UniqueConstraint("farm_id", "code", name="uq_customers_farm_code"), mysql_charset="utf8mb4")
    op.create_table("sales_orders", sa.Column("id", mysql.BIGINT(unsigned=True), primary_key=True, autoincrement=True), sa.Column("farm_id", mysql.BIGINT(unsigned=True), nullable=False), sa.Column("order_no", sa.String(30), nullable=False), sa.Column("customer_id", mysql.BIGINT(unsigned=True), nullable=False), sa.Column("warehouse_id", mysql.BIGINT(unsigned=True), nullable=False), sa.Column("sale_date", sa.Date(), nullable=False), sa.Column("status", sa.String(20), server_default="DRAFT", nullable=False), sa.Column("total_amount", sa.Numeric(16,2), server_default="0", nullable=False), sa.Column("received_amount", sa.Numeric(16,2), server_default="0", nullable=False), sa.Column("notes", sa.String(500)), sa.Column("posted_at", sa.DateTime()), sa.Column("posted_by_id", mysql.BIGINT(unsigned=True)), sa.Column("created_by_id", mysql.BIGINT(unsigned=True), nullable=False), sa.Column("created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False), sa.ForeignKeyConstraint(["farm_id"], ["farms.id"], ondelete="RESTRICT"), sa.ForeignKeyConstraint(["customer_id"], ["customers.id"], ondelete="RESTRICT"), sa.ForeignKeyConstraint(["warehouse_id"], ["warehouses.id"], ondelete="RESTRICT"), sa.ForeignKeyConstraint(["posted_by_id"], ["users.id"], ondelete="RESTRICT"), sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="RESTRICT"), sa.UniqueConstraint("farm_id", "order_no", name="uq_sales_orders_farm_no"), mysql_charset="utf8mb4")
    op.create_table("sales_order_lines", sa.Column("id", mysql.BIGINT(unsigned=True), primary_key=True, autoincrement=True), sa.Column("sales_order_id", mysql.BIGINT(unsigned=True), nullable=False), sa.Column("item_id", mysql.BIGINT(unsigned=True), nullable=False), sa.Column("quantity", sa.Numeric(14,3), nullable=False), sa.Column("unit_price", sa.Numeric(16,4), nullable=False), sa.Column("amount", sa.Numeric(16,2), nullable=False), sa.Column("unit_cost", sa.Numeric(16,4), server_default="0", nullable=False), sa.ForeignKeyConstraint(["sales_order_id"], ["sales_orders.id"], ondelete="CASCADE"), sa.ForeignKeyConstraint(["item_id"], ["items.id"], ondelete="RESTRICT"), sa.CheckConstraint("quantity > 0", name="ck_sales_lines_quantity_positive"), mysql_charset="utf8mb4")
    op.create_table("payments", sa.Column("id", mysql.BIGINT(unsigned=True), primary_key=True, autoincrement=True), sa.Column("farm_id", mysql.BIGINT(unsigned=True), nullable=False), sa.Column("payment_no", sa.String(30), nullable=False), sa.Column("direction", sa.String(10), nullable=False), sa.Column("business_date", sa.Date(), nullable=False), sa.Column("amount", sa.Numeric(16,2), nullable=False), sa.Column("method", sa.String(20), nullable=False), sa.Column("customer_id", mysql.BIGINT(unsigned=True)), sa.Column("sales_order_id", mysql.BIGINT(unsigned=True)), sa.Column("notes", sa.String(500)), sa.Column("created_by_id", mysql.BIGINT(unsigned=True), nullable=False), sa.Column("created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False), sa.ForeignKeyConstraint(["farm_id"], ["farms.id"], ondelete="RESTRICT"), sa.ForeignKeyConstraint(["customer_id"], ["customers.id"], ondelete="RESTRICT"), sa.ForeignKeyConstraint(["sales_order_id"], ["sales_orders.id"], ondelete="RESTRICT"), sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="RESTRICT"), sa.CheckConstraint("amount > 0", name="ck_payments_amount_positive"), sa.UniqueConstraint("farm_id", "payment_no", name="uq_payments_farm_no"), mysql_charset="utf8mb4")

def downgrade():
    op.drop_table("payments"); op.drop_table("sales_order_lines"); op.drop_table("sales_orders"); op.drop_table("customers")
